'use client'

import { useEffect, useState } from 'react'
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Camera, ChevronDown, ChevronLeft, ChevronRight, Menu as MenuIcon, Minus, Plus, Sparkles, X } from 'lucide-react'
import { business, categories, combos, gallery, menuItems } from '@/data/menu'

const cream = '#F4EEDC'

function SectionKicker({ children }: { children: string }) { return <p className="kicker">{children}</p> }
function Spark({ className = '' }: { className?: string }) { return <Sparkles aria-hidden="true" className={`spark ${className}`} size={18} /> }

export default function TinyTreatsSite() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selected, setSelected] = useState<(typeof menuItems)[number] | null>(null)
  const [page, setPage] = useState(1)
  const [zoom, setZoom] = useState(1)

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'ArrowRight') setPage((p) => Math.min(7, p + 1)); if (e.key === 'ArrowLeft') setPage((p) => Math.max(1, p - 1)); if (e.key === 'Escape') setSelected(null) }
    window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey)
  }, [])

  const goMenu = (target = 1) => { setPage(target); document.getElementById('menu')?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false) }
  return <div className="site-shell">
    <header className="nav-wrap"><nav className="nav container">
      <a className="brand" href="#home" aria-label="Tiny Treats home"><span>TINY</span> TREATS</a>
      <div className={`nav-links ${menuOpen ? 'is-open' : ''}`}>
        {[['Home', '#home'], ['Menu', '#menu'], ['Treats', '#treats'], ['Combos', '#combos'], ['Gallery', '#gallery'], ['Visit Us', '#visit']].map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}
      </div>
      <button className="nav-cta" onClick={() => goMenu()}><span>VIEW MENU</span><ArrowUpRight size={16} /></button>
      <button className="mobile-menu" aria-label="Toggle navigation" onClick={() => setMenuOpen((o) => !o)}>{menuOpen ? <X /> : <MenuIcon />}</button>
    </nav></header>

    <main>
      <section id="home" className="hero section-pad"><div className="hero-noise" /><div className="hero-copy container">
        <div className="hero-words"><SectionKicker>WELCOME TO OUR LITTLE WORLD</SectionKicker><h1>TINY<br /><em>TREATS</em></h1><p className="hero-tagline">TINY BITES,<br /><span>BIG HAPPINESS.</span></p><p className="hero-sub">Sweet treats, creamy scoops, chocolatey desserts and café favourites — all in one tiny place.</p><div className="button-row"><button className="button button-orange" onClick={() => goMenu()}>EXPLORE MENU <ArrowRight size={17} /></button><a className="text-link" href="#treats">SEE OUR TREATS <ArrowDown size={15} /></a></div></div>
        <div className="hero-art" aria-label="Dessert collage"><div className="hero-orbit" /><Spark className="spark-one" /><Spark className="spark-two" /><div className="sticker sticker-top">made<br /><b>tiny</b></div><img className="hero-dessert hero-dessert-main" src={menuItems[3].image} alt="Chocolate dessert with marshmallows" /><img className="hero-dessert hero-dessert-side" src={menuItems[0].image} alt="Colourful popsicle" /><div className="hero-badge">SWEET<br /><span>SPOT</span></div></div>
      </div><div className="hero-bottom container"><span>EST. FOR BIG CRAVINGS</span><span>SCROLL TO EXPLORE <ChevronDown size={15} /></span></div></section>

      <section id="treats" className="light-section section-pad"><div className="container"><div className="section-head"><div><SectionKicker>THE LITTLE THINGS</SectionKicker><h2>TINY TREATS<br /><em>SIGNATURES</em></h2></div><p>Big flavour, tiny packages. Meet the treats that make our little corner of the world worth finding.</p></div><div className="treat-grid">{menuItems.slice(0, 5).map((item, i) => <article className={`treat-card card-${i + 1}`} key={item.id} onClick={() => setSelected(item)}><div className="card-image"><img src={item.image} alt={item.name} loading="lazy" /><span className="card-number">0{i + 1}</span></div><div className="card-info"><div><p className="card-category">{item.category}</p><h3>{item.name}</h3></div><span className="price">{item.price}</span></div><button className="card-link" aria-label={`View ${item.name} in menu`} onClick={(e) => { e.stopPropagation(); goMenu(item.page) }}>VIEW IN MENU <ArrowUpRight size={15} /></button></article>)}</div></div></section>

      <section id="menu" className="menu-section section-pad"><div className="container"><div className="section-head menu-head"><div><SectionKicker>THE MAIN EVENT</SectionKicker><h2>OPEN THE<br /><em>MENU</em></h2></div><p>Flip through the real Tiny Treats experience — seven pages of tiny bites and big happiness.</p></div><div className="flipbook-area"><button className="flip-arrow left" aria-label="Previous page" onClick={() => setPage((p) => Math.max(1, p - 1))}><ChevronLeft /></button><div className="book-shell"><div className="book-page" style={{ transform: `scale(${zoom})` }}>{page === 1 ? <CoverPage /> : <MenuContentPage page={page} />}</div><span className="page-corner">{page} / 7</span></div><button className="flip-arrow right" aria-label="Next page" onClick={() => setPage((p) => Math.min(7, p + 1))}><ChevronRight /></button></div><div className="menu-controls"><button onClick={() => setPage((p) => Math.max(1, p - 1))}><ArrowLeft size={16} /> PREVIOUS</button><span>PAGE {page} / 7</span><button onClick={() => setPage((p) => Math.min(7, p + 1))}>NEXT <ArrowRight size={16} /></button><span className="control-divider" /><button aria-label="Zoom out" onClick={() => setZoom((z) => Math.max(.8, z - .1))}><Minus size={16} /></button><button aria-label="Zoom in" onClick={() => setZoom((z) => Math.min(1.2, z + .1))}><Plus size={16} /></button><button aria-label="Reset zoom" onClick={() => setZoom(1)}>RESET</button></div><p className="swipe-hint">SWIPE TO FLIP <ArrowRight size={15} /></p><div className="category-row">{categories.map(([name, target]) => <button key={name} onClick={() => setPage(target)} className={page === target ? 'active' : ''}>{name}</button>)}</div></div></section>

      <section id="combos" className="combo-section section-pad"><div className="container"><div className="section-head"><div><SectionKicker>FOR THE HUNGRY HEART</SectionKicker><h2>HUNGER<br /><em>COMBOS</em></h2></div><p>Big cravings deserve bigger treats. Pick a pairing, bring a friend, make a moment.</p></div><div className="combo-grid">{combos.map((combo, i) => <article className={`combo-card ${i === 3 ? 'combo-featured' : ''}`} key={combo.name}><img src={combo.image} alt="" loading="lazy" /><div className="combo-overlay"><span>COMBO 0{i + 1}</span><h3>{combo.name}</h3><strong>₹{combo.price.replace(' rs', '')}</strong><button onClick={() => goMenu(7)}>EXPLORE <ArrowUpRight size={15} /></button></div></article>)}</div></div></section>

      <section id="gallery" className="light-section section-pad"><div className="container"><div className="section-head"><div><SectionKicker>THE TINY TREATS WALL</SectionKicker><h2>A LITTLE<br /><em>GALLERY</em></h2></div><p>Follow the colour, the crunch and the chocolate trail.</p></div><div className="gallery-grid">{gallery.map((image, i) => <figure key={image.title} className={`gallery-item gallery-${i + 1}`}><img src={image.image} alt={image.title} loading="lazy" /><figcaption><span>{image.kind}</span><b>{image.title}</b></figcaption></figure>)}</div></div></section>

      <section className="why-section section-pad"><div className="container"><div className="why-intro"><SectionKicker>THE TINY TREAT MINDSET</SectionKicker><h2>WHY <em>TINY</em><br />TREATS?</h2><Spark /></div><div className="why-grid">{[['SWEET', 'Desserts made for cravings.'], ['CHILL', 'Ice creams and popsicles for every mood.'], ['CRAVE', 'Chocolatey desserts, shakes and café favourites.'], ['SHARE', 'Combos and treats made for good moments.']].map(([title, copy], i) => <div className="why-card" key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>

      <section id="visit" className="visit-section section-pad"><div className="container visit-inner"><div><SectionKicker>THE BEST PART IS SHOWING UP</SectionKicker><h2>COME GRAB<br />A <em>TINY TREAT</em></h2><p>Our doors are open for tiny bites, big smiles and whatever you’re craving today.</p><div className="button-row"><button className="button button-orange" disabled={!business.address}>GET DIRECTIONS <ArrowUpRight size={16} /></button><button className="button button-outline" disabled={!business.phone}>CALL NOW <ArrowUpRight size={16} /></button></div></div><div className="visit-card"><div className="pin-art">TT</div><div><span>FIND US HERE</span><h3>YOUR NEXT<br /><em>HAPPY PLACE</em></h3><p>{business.address || 'Address coming soon'}</p></div><div className="visit-meta"><span>OPENING HOURS</span><b>{business.hours || 'Hours coming soon'}</b></div></div></div></section>

      <section className="social-section section-pad"><div className="container social-head"><div><SectionKicker>COME SAY HI ONLINE</SectionKicker><h2>FOLLOW THE<br /><em>TINY TREATS</em></h2></div><a className="social-link" href={business.instagram || '#'}>MORE TINY TREATS. MORE BIG HAPPINESS. <Camera size={20} /></a></div></section>
    </main>

    <footer className="footer"><div className="container footer-top"><a className="brand" href="#home"><span>TINY</span> TREATS</a><p>TINY BITES,<br /><em>BIG HAPPINESS.</em></p><div className="footer-links">{['Home', 'Menu', 'Treats', 'Combos', 'Gallery', 'Visit Us'].map((x) => <a key={x} href={`#${x === 'Home' ? 'home' : x.toLowerCase().replace(' ', '-')}`}>{x}</a>)}</div><a className="footer-social" href={business.instagram || '#'}><Camera size={19} /> INSTAGRAM</a></div><div className="container footer-bottom"><span>© 2026 Tiny Treats. All rights reserved.</span><span>MADE FOR BIG CRAVINGS <Spark size={13} /></span></div></footer>
    <button className="floating-menu" onClick={() => goMenu()}><span>VIEW MENU</span><ArrowUpRight size={18} /></button>
    {selected && <div className="modal-backdrop" role="dialog" aria-modal="true" onClick={() => setSelected(null)}><div className="item-modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close"><X /></button><img src={selected.image} alt={selected.name} /><div><SectionKicker>{selected.category}</SectionKicker><h2>{selected.name}</h2><p>{selected.description}</p><strong>{selected.price}</strong><button className="button button-orange" onClick={() => { setSelected(null); goMenu(selected.page) }}>FIND IT IN MENU <ArrowUpRight size={16} /></button></div></div></div>}
  </div>
}

function CoverPage() { return <div className="cover-page"><div className="cover-lines" /><Spark className="cover-spark" /><span className="cover-small">THE TINY TREATS MENU</span><h3>TINY<br /><em>TREATS</em></h3><p>TINY BITES,<br /><b>BIG HAPPINESS.</b></p><div className="cover-pops"><span>●</span><span>●</span><span>●</span></div><span className="cover-footer">SWEET THINGS INSIDE</span></div> }
function MenuContentPage({ page }: { page: number }) { const content: Record<number, { title: string; groups: [string, string[]][] }> = { 2: { title: 'TINY TREATS\nSIGNATURE ITEMS', groups: [['THE CLASSICS', ['Mini Popsicles', 'Nutella French Toast', 'Brownie Bowls', 'Skillet S’mores', 'Sandwich', 'Mini Nutella Pancakes']]] }, 3: { title: 'MINI\nPOPSICLES', groups: [['CHOCOLATEY COLLECTION', ['Milk Chocolate', 'Chocolate Truffle', 'Tiramisu', 'Oreo Vanilla', 'Mint Chocochip', 'Dubai Chocolate', 'Chocolate & Browie Chunks']], ['NUTS & FRUITY COLLECTION', ['Watermelon', 'Strawberry Vanilla Matcha', 'Pistachio', 'Mango', 'Kulfi', 'Grape', 'Caramel Nuts', 'Guava', 'Chilli Guava']]] }, 4: { title: 'SIGNATURE\nDESSERTS', groups: [['SWEET STUFF', ['Skillet S’mores · 240 rs', 'Brownie Bowls · 280 rs', 'Nutella French Toast · 275 rs', 'Paris Cocoa Cup · 200 rs', 'Hot Brownie With Ice Cream · 210 rs', 'Berry Mallow Platter · 270 rs', 'Sweet Crepe Roll · 240 rs', 'Mini Nutella Pancakes · 205 rs']]] }, 5: { title: 'COFFEE +\nMILKSHAKES', groups: [['COFFEE', ['Americano · 110 rs', 'Plain Cappuccino · 135 rs', 'Hazelnut Cappuccino · 150 rs', 'Iced Americano · 130 rs', 'Iced Caramel Latte · 155 rs', 'Cold Coffee With Icecream · 170 rs']], ['MILKSHAKES', ['Oreo Shake · 180 rs', 'Kit Kat Shake · 200 rs', 'Mango Shake · 245 rs', 'Belgian Chocolate Shake · 250 rs']], ['SCOPING FLAVOURS', ['Dubai Chocolate · S 99 / M 120', 'Chocolate Truffle · S 99 / M 120']]] }, 6: { title: 'SAVOURY\nBITES', groups: [['SAVOURY', ['Chicken Burger · 180 rs', 'Veg Burger · 160 rs', 'Chicken Sandwich · 190 rs', 'Veg Chicken · 130 rs', 'Salted Fries · 110 rs', 'Peri Peri Fries · 135 rs', 'Chicken Nuggets 6 pcs · 150 rs']], ['EXTRAS', ['Monster · 120 rs', 'Diet Coke · 40 rs', 'Sprite · 20 rs', 'Thumbs Up · 20 rs', 'Water Bottle · 10 rs']]] }, 7: { title: 'HUNGER\nCOMBOS', groups: [['BIG CRAVINGS', ['Chicken Burger + Peri Peri Fries + Extras · 349 rs', 'Veg Sandwich + Salted Fries + Extras · 300 rs', 'Mini Pancakes + Mini Pops 4 + Cold Coffee · 410 rs', 'Skillet S’mores + Chocolate Pops 3 + Belgian Chocolate Shake · 509 rs']]] } }; const current = content[page]; return <div className="menu-content"><div className="menu-page-top"><span>tiny treats</span><span>0{page}</span></div><h3>{current.title.split('\n').map((x) => <span key={x}>{x}</span>)}</h3>{current.groups.map(([group, items]) => <div className="menu-group" key={group}><h4>{group}</h4>{items.map((item) => <div className="menu-line" key={item}><span>{item.split(' · ')[0]}</span><b>{item.includes(' · ') ? item.split(' · ')[1] : ' '}</b></div>)}</div>)}<div className="menu-page-bottom"><Spark /> <span>TINY BITES, BIG HAPPINESS.</span></div></div> }
